[build]
builder = "dockerfile"

[[services]]
name = "strapi"
dockerfilePath = "strapi/Dockerfile"

[services.deploy]
startCommand = "npm run start"

[[services]]
name = "bot"
dockerfilePath = "bot/Dockerfile"
